---

- name: Install dependencies for compiling node-gyp
  action: apt pkg="{{ item }}" state=present
  with_items:
    - make
    - g++

- name: Install maildev
  npm: name=maildev global=yes state=present

- name: Create startup script for maildev
  template: src=maildev.conf.j2 dest=/etc/init/maildev.conf mode=0755
  notify: restart maildev